version: '3.9'

services:
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '9999:9999'
    depends_on:
      - api-1
      - api-2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 24m

  redis:
    image: redis:7.2-alpine
    command: ['redis-server','--maxmemory','60mb','--maxmemory-policy','allkeys-lru']
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 64m

  api-1:
    build: .
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PROC_DEFAULT_URL=http://host.docker.internal:8001
      - PROC_FALLBACK_URL=http://host.docker.internal:8002
      - TOKEN=${TOKEN:-123}
      - PORT=3000
    command: ['bun','src/server.ts']
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64m

  api-2:
    build: .
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PROC_DEFAULT_URL=http://host.docker.internal:8001
      - PROC_FALLBACK_URL=http://host.docker.internal:8002
      - TOKEN=${TOKEN:-123}
      - PORT=3000
    command: ['bun','src/server.ts']
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64m

  worker:
    build: .
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PROC_DEFAULT_URL=http://host.docker.internal:8001
      - PROC_FALLBACK_URL=http://host.docker.internal:8002
      - TOKEN=${TOKEN:-123}
    command: ['bun','src/worker.ts']
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 96m
