version: '3.9'
services:
  redis:
    image: redis:7.2-alpine
    ports: ['6381:6381']
  api:
    build: .
    environment:
      - REDIS_URL=redis://redis:6381
      - PROC_DEFAULT_URL=http://host.docker.internal:8001
      - PROC_FALLBACK_URL=http://host.docker.internal:8002
      - TOKEN=123
      - PORT=3000
    ports: ['3000:3000']
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on: [redis]
